apiVersion: v1
kind: Namespace
metadata:
  name: my-expense-helm
  labels:
    app: mysql
    tier: db
    project: expense
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: my-expense-helm
  labels:
    app: mysql
    tier: db
    project: expense
spec:
  # modify replicas according to your case
  replicas: 1
  selector:
    matchLabels:
      app: mysql
      tier: db
      project: expense
  template:
    metadata:
      labels:
        app: mysql
        tier: db
        project: expense
    spec:
      containers:
      - name: mysql
        image: joindevops/mysql:{{ .Values.deployment.version}}
---
apiVersion: v1
kind: Service
metadata: 
  name: mysql-helm
  namespace: my-expense-helm
spec:
  selector:
    app: mysql
    tier: db
    project: expense
  ports:
  - name: mysql-service-port
    protocol: TCP
    port: {{.Values.service.port}}
    targetPort: 3306