apiVersion: v1
kind: Service
metadata: 
  name: nginx
spec:
  selector:
    project: expense
    environment: dev
    org: joindevops
  ports:
  - name: sample-service-port
    protocol: TCP
    port: {{.Value.service.port}}
    targetPort: 80